---
npm:
  platforms:
    - name: linux
      os: ubuntu
      packages:
        - libudev-dev
      architecture: x86_64
      node_versions:
        - "10"
        - "12"
        - "14"
        - "16"
    - name: linux
      os: ubuntu
      packages:
        - libudev-dev
      architecture: x86
      node_versions:
        - "10"
        - "12"
        - "14"
        - "16"
    # - name: darwin
    #   os: macos
    #   packages:
    #     - libudev-dev
    #   architecture: x86_64
    # - name: windows
    #   os: windows
    #   packages:
    #     - libudev-dev
    #   architecture: x86_64
    # - name: windows
    #   os: windows
    #   packages:
    #     - libudev-dev
    #   architecture: x86
