# appveyor file
# http://www.appveyor.com/docs/appveyor-yml
image: Visual Studio 2015

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\Users\appveyor\AppData\Local\Temp\chocolatey -> appveyor.yml

# what combinations to test
environment:
  global:
    nodejs_version: "6.10.3"

platform:
  - x86
  - x64

matrix:
  fast_finish: true

install:
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:Platform
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm test
